### ISSUE TITLE
Migrate off of deprecated `Dimensions.removeEventListener`

### ISSUE THREAD

**Issue by gantonious** [Shopify/restyle#107]
As of React Native v0.65 `Dimensions.removeEventListener` has been deprecated and using it will emit warnings. This can add significant noise to the console if you have many restyle components unmounting. We have a couple of options for migration here:

### Option 1) Leave our react-native peer dependency at `>=0.59.0` and conditionally call deprecated API

With React Native v0.65 `Dimensions.addEventListener` has been updated to return a `EventSubscription` instead of void. We can check if a `remove` property exists on the returned value and if so use the new `remove` API else use the old  `Dimensions.removeEventListener`.

### Option 2) Bump our react-native peer dependency to `>=0.61.0` and use the builtin `useWindowDimensions` API 

This removes our need to interact with `Dimensions` and its deprecated APIs: https://reactnative.dev/docs/usewindowdimensions. Though this will bump our minimum supported `react-native` version potentially breaking compatibility for consumers.

Dimensions usage:

https://github.com/Shopify/restyle/blob/22cd0d3b229fdf425c81843a1ad9903851770d69/src/hooks/useDimensions.ts#L6-L22

**Comment by dejanr** [comment]
I just upgraded to 0.65 and discovered this. Anyone looking into this, i can help with PR if needed.

**Comment by nelyousfi** [comment]
Just published the version 1.5.0 with the fix.
