### ISSUE TITLE
Invariant violation: no callback found with cbID

### ISSUE THREAD

**Issue by josephmbeveridge** [Shopify/restyle#11]
I created a starter app using `react-native init` and https://github.com/react-native-community/react-native-template-typescript. Then added `restyle` as a package and set up a `theme.ts` identical to the example on the README.

I get this error if I try to add the `ThemeProvider` to the root of the basic RN starting app:
<img width="417" alt="Screen Shot 2020-03-25 at 2 50 58 PM" src="https://user-images.githubusercontent.com/3857356/77574342-3cb0c400-6ea8-11ea-85c4-72bb4bdbe112.png">

**Comment by josephmbeveridge** [comment]
Looks like it may be due to some weird monorepo bugs. Will close for now

**Comment by acollazomayer** [comment]
@josephmbeveridge Did you manage to solve this?

**Comment by sousadgaspar** [comment]
I'm also facing the same issue. @josephmbeveridge did you find the solution?

**Comment by sousadgaspar** [comment]
Hopefully I end up solving the issue. This issue had appeared after the installation of the @react-native-community/cameraroll library. To solve, I simply removed the library via yarn remove and installed again.

Hope it helps.

**Comment by nawin97** [comment]
Still facing the issue

**Comment by mikeRChambers610** [comment]
I am having this issue. Why is this issue closed with no solution?

**Comment by this-is-jassa** [comment]
Facing the same Issue! 

Invariant Violation: No callback found with cbID 13126 and callID 6563 for  StripeSdk.confirmPaymentMethod - most likely the callback was already invoked. Args: '[{"error":{"stripeErrorCode":null,"declineCode":null,"localizedMessage":"Unhandled error occured","message":"Unhandled error occured","type":null,"code":"Unknown"}}]'
