### ISSUE TITLE
Question: relative REM unit / extended style sheets

### ISSUE THREAD

**Issue by frankcalise** [Shopify/restyle#13]
Is there a way to use REM with this library? Can it be used in with react-native-extended-stylesheet?

**Comment by JoelBesada** [comment]
Hmm, not by default but you might be able to add support for this locally in your project. If you use the [`useRestyle` hook](https://github.com/Shopify/restyle/tree/1b7bfb47da0172d6016623313fbb0c46ccf6ec12#custom-components), you'll get all the final style values and have a chance to further process them before setting them on a component. I've never used react-native-extended-stylesheet but perhaps something like this would be possible: 

```tsx
const Component = (props: Props) => {
  const props = useRestyle(restyleFunctions, rest);
  // A function (or hook) that further processes the style values to add support for REM etc.
  // Not sure if something like this is readily available from react-native-extended-stylesheet.
  const extendedStyle = processStyle(props.style);
  return (
      <View {...props} style={extendedStyle} />
  );
};
```

**Comment by frankcalise** [comment]
Thanks I will give that a shot :)
