### ISSUE TITLE
How to useRestyle with custom variants in Restyle 2.0

### ISSUE THREAD

**Issue by HurrellT** [Shopify/restyle#147]
Hi! I'm building a component lib creating variants for my components.

I'm creating variants like this:

```tsx
const inputVariants = createVariant<Theme, 'inputVariants'>({
  themeKey: 'inputVariants',
});
```

then using useRestyle to inject the styles in the corresponding section of my component like this

```tsx
  const InputStyle = useRestyle([inputVariants, spacing], {
    variant: currentVariant,
    ...remainingStyles,
  });
```

Now, with restyle update 2.0, useRestyle is not working with variants, even after being wrapped with `composeRestyleFunctions` and I'm not finding the way to make it work. Am I using it incorrectly?

Thanks!

**Comment by sbalay** [comment]
@HurrellT  Could you create and share a repo with the code and instructions to reproduce the unexpected behaviour you describe?

**Comment by HurrellT** [comment]
> 

Hi! I made a repo with an example of what I'm expecting to do.
https://github.com/HurrellT/restyleVariantsExample
Thanks!

**Comment by sbalay** [comment]
Thanks for that @HurrellT!

I've created a PR to your repo with a workaround, would you mind playing around with that and letting us know if you still face any issues?

**Comment by fortmarek** [comment]
Closing as stale.

**Comment by isaachinman** [comment]
@fortmarek Is there any example in the documentation anywhere of how to achieve this?
