### ISSUE TITLE
Can not use variant

### ISSUE THREAD

**Issue by Jalson1982** [Shopify/restyle#15]
Hello here is my basic theme setup:

`const palette = {
  white: '#FFFFFF',
  black: '#000000',
  darkGray: '#4D4D4D',
  mediumGray: '#CACACA',
  lightGray: '#E9E9E9',
  primaryColor: '#46DB72',
  secondaryColor: '#00BCFF',
  thirdColor: '#2CDCA0',
  successColor: '#94DE45',
  errorColor: '#EF4836',
  warningColor: '#FF8C2F',
  facebookColor: '#3B5998',
  backgroundDarkenColor: 'rgba(0,0,0,0.4)',
  skyBlue: '#02bcff'
};

const theme = {
  colors: {
    mainBackground: palette.white,
    cardPrimaryBackground: palette.white,
    buttonPrimaryBackgroundColor: palette.primaryColor,
    buttonFacebookColor: palette.facebookColor,
    buttonWhiteColor: palette.white,
    inactiveBackgroundColor: palette.mediumGray
  },
  spacing: {
    es: 5,
    s: 8,
    m: 20,
    l: 24,
    xl: 40
  },
  breakpoints: {
    phone: 0,
    tablet: 768
  },
  fontWeights: {
    baseFontWeight: '400',
    boldFontWeight: '700',
    altFontWeight: '900'
  },
  fontSizes: {
    small: 12,
    normal: 14,
    medium: 16,
    medim_large: 18,
    large: 20,
    extraLarge: 22
  },
  fontFamily: {
    baseFontFamily: 'Lato'
  },
  textVariants: {
    logoHeading: {
      color: 'mainBackground',
      padding: {phone: 'es', tablet: 's'},
      fontSize: {phone: 18, tablet: 30},
      fontFamily: 'Lato'
    }
  },
  buttonVariants: {
    primaryButton: {
      width: {phone: 200, tablet: 300},
      height: 50,
      borderRadius: 20,
      marginBottom: 20,
      justifyContent: 'center',
      alignItems: 'center'
    }
  }
};

export default theme;
`

And i want to use variant in card I did this:

` const variant = createVariant({
    themeKey: 'buttonVariants',
    defaults: {
      height: 50
    }
  });

  const Card = createRestyleComponent([variant]);`

And when want to use always get error: Value '20' does not exist in theme['spacing']

What am I doing wrong ?

**Comment by JoelBesada** [comment]
Hi! In `buttonVariants` in your theme, you need to specify `marginBottom` as one of your spacing variables, so if you want 20 pixels here it should be `marginBottom: 'm'`

**Comment by Jalson1982** [comment]
It works thx. How you handle dynamic values? If I have predefined Box with alignment and based on props it can be flex:1 or flex:0.5?

**Comment by Jalson1982** [comment]
Also, I have noticed if I have in theme spacing, and I want in Box component padding-bottom that depends on safe area I can not pass number because it looks in theme for those values. Any way to override it on fly ( i know I could write styles but do you provide something )

**Comment by Jalson1982** [comment]
Also what I have noticed if you like RectButton from gesture handler you can not put any style there then to a classic react-native extended stylesheet and I really wanted to avoid it :(. Maybe I do not know how to do it, but it seems it is a limitation that we can not wrap those components or give them variant.

**Comment by Jalson1982** [comment]
@JoelBesada can you please when having a time provide an answer is it possible to apply a style to TouchableOpacity or any other component besides Text and View. I tried 100 options could not make it to work.

**Comment by JoelBesada** [comment]
The only way to directly pass a padding as a number to a Box component is through the `style` property right now. 

For your other questions, I think you'll want to look into the examples for custom components here https://github.com/Shopify/restyle/tree/2a59dcc0c765a0f1f3afba557cea9a5a85818a49#custom-components. With the `useRestyle` hook you gain more control over what you do with the props and where you're passing them, so that might help you. Also, if you're looking to create a component that accepts the same styling props as a Box but want to use another underlying component, `createBox` can accept that underlying component as an argument:

```tsx
import {Image} from 'react-native'
import {createBox} from '@shopify/restyle'
import {Theme} from './theme';

const ImageBox = createBox<Theme, React.ComponentProps<typeof Image>>(Image)
```

Same goes for `createRestyleComponent` if you just want some of the restyle functions: 
```tsx
import {TouchableOpacity} from 'react-native'
import {
  createRestyleComponent,
  spacing,
  layout,
  SpacingProps,
  LayoutProps,
} from '@shopify/restyle';
import {Theme} from './theme'

type Props = SpacingProps<Theme> & LayoutProps<Theme>
const TouchableBox = createRestyleComponent<Props>([
  spacing,
  layout,
], TouchableOpacity)

export default Card
```

**Comment by Jalson1982** [comment]
Aaa so we can pass custom component... what a plunker I am... thx 1000 times mate!!!
