### ISSUE TITLE
Is this Library abandoned?

### ISSUE THREAD

**Issue by dawidvdh** [Shopify/restyle#184]
Hi! really like the idea/concept of the library! I am busy making a decision on whether to use this library however it seems to be abandoned? Would just like a clarifying answer as there is a bunch of old issues and the code base hasn't been updated in some time.

**Comment by fortmarek** [comment]
Hey!

The library is still heavily used at Shopify and we actively maintain it. However, we haven't been able to give a lot of support to the external issues and PRs but it's something we want to get better at. We are making some changes internally and we plan to spend more active time on this library the next year. Let us know if there are any high-priority issues you think we should look at.

**Comment by huschu** [comment]
Thank you for your comment, that is very good to hear. 
Maybe you could have a look at the `fontVariant` [issue](https://github.com/Shopify/restyle/issues/169#issuecomment-1205118667), it's a bit annoying.

**Comment by fortmarek** [comment]
Closing this issue as the answer is the short answer is "no". 

@huschu We'll consider this looking into this early next year, PRs are also always welcome 😇

**Comment by neiker** [comment]
Looks like it is abandoned after all
