### ISSUE TITLE
How to wrap KeyboardAvoidingView in Box?

### ISSUE THREAD

**Issue by fregayeg** [Shopify/restyle#189]
Hello! 

I'd like to know how to wrap `KeyboardAvoidingView` in ``Box`` like we do with ``View``. I'd equally ask, is it good to do this ? 

thanks in advance

**Comment by fortmarek** [comment]
`Box` is only a wrapper of a `View` that translates your `theme` values to `style` that `View` can understand. So, whatever you can do with `View`, you should be to do with `Box`. If necessary, please follow up with your questions in the [discussions](https://github.com/Shopify/restyle/discussions) instead as issues are now primarily for flagging bugs.
