### ISSUE TITLE
The documents point to functions that have not been published in npm.

### ISSUE THREAD

**Issue by andrefedev** [Shopify/restyle#29]
Last update was 5 months ago, documentation points to createTheme which is not available in version 1.0.4. So for some reason I try to install this repository with npm install github:shopify/restyle# master but it doesn't install.

**Comment by JoelBesada** [comment]
Ah, sorry about that! I'm planning to push a new version to NPM today that will include the createTheme function, but until then you can just create your theme as a plain object without passing it to the functoin: `export const theme = { /* colors, spacing, etc */ }`
