### ISSUE TITLE
Module has no exported  member 'createTheme'

### ISSUE THREAD

**Issue by its-tayo** [Shopify/restyle#31]
Hello all, trying out this package for the first time. I can't seem to get my theme setup following instructions in the documentation. Please see attached snapshot. I've got version 1.0.4 installed btw.

<img width="813" alt="Screenshot 2020-07-25 at 12 23 31" src="https://user-images.githubusercontent.com/29132110/88456597-a0f38c80-ce76-11ea-859e-154bf741972b.png">

**Comment by JoelBesada** [comment]
Sorry, the documentation was referring to a function that hadn't yet been published. I've just pushed the latest version to NPM, you should find this under version 1.1.0.
