### ISSUE TITLE
Question: How to use variants with the useRestyle hook

### ISSUE THREAD

**Issue by its-tayo** [Shopify/restyle#34]
Can you please include an example of how to use variants with useRestyle hook? Thanks.

**Comment by jackspiva** [comment]
I'm also confused by this, would love an example.

**Comment by negrudev** [comment]
I'm also interested. Thanks

**Comment by JoelBesada** [comment]
I found that the types for `useRestyle` are not accepting a function created with `createVariant` due to a bug right now, but here's an example with a workaround for that: 
```tsx
const cardVariant = createVariant({themeKey: 'cardVariants'});
const Card = (props: Props) => {
  const restyledProps = useRestyle([cardVariant as any], props);
  return <View {...restyledProps} />;
};
```

I'll make sure to fix the bug so the `as any` part can be avoided.

**Comment by its-tayo** [comment]
Thank you @JoelBesada, we can close this when the TS bug is fixed.

**Comment by jdstregz** [comment]
Could there be a proper example added for this?
