### ISSUE TITLE
TypeError: undefined is not a function (near '...(0, _restyle.createTheme)...')

### ISSUE THREAD

**Issue by andrefedev** [Shopify/restyle#35]
I am trying to implement theme with createTheme but when launching my application in android it throws the following error:

    17:48:10.908	client_log	TypeError: undefined is not a function (near '...(0, _restyle.createTheme)...')
    17:48:10.909	client_log	Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
    17:48:23.920	client_log	TypeError: undefined is not a function (near '...(0, _restyle.createTheme)...')
    17:48:23.920	client_log	Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

    this launch the error;
    const theme = createTheme({// theme options});
    this work.
    const theme = {//theme};

**Comment by andrefedev** [comment]
The problem was solved, removing node_modules and running npm install again. Thank you.

**Comment by sperezm97** [comment]
hi @andrefedev how do you resolve this? it happened to me on react-native: "0.70.2"  👀
