### ISSUE TITLE
Typescript issues with forwardRef

### ISSUE THREAD

**Issue by sarmad1995** [Shopify/restyle#40]
HI, 
Thanks for a great library, I have been using it and seems good. Previously I used to use styled-system but it was not fully supported for react-native

I am facing one issue regarding forwarding the refs.

here is my example, What i want to achieve is that I want to create a TextInput with the style props

```jsx
import React, { forwardRef } from "react";
import { createBox, ColorProps } from "@shopify/restyle";
import {
  TextInput as RNTextInput,
  TextInputProps as RNTextInputProps,
} from "react-native";
import { Theme } from "styles/theme";

const TextInputBase = createBox<Theme, RNTextInputProps>(RNTextInput);

type TextInputProps = React.ComponentPropsWithRef<typeof TextInputBase> &
  ColorProps<Theme> & {
    error?: string | boolean;
  };

export const TextInput = forwardRef<typeof TextInputBase, TextInputProps>(
  (props, ref) => {
    return <TextInputBase ref={ref} {...props} />;
  },
);
```

But ts throws an error that Ref doesn't exist in TextInputBase.

I could have used `useRestyle` and customise it to my needs but in that case my variants won't work :|
Help would be appreciated. 

**UPDATE**

I figured out a way to have variants and `useRestyle` but there are some issues with ts. 
Everything works fine in this example except there is ts error for the restylecontainerarray,

```jsx
import React, { forwardRef } from "react";
import {
  ColorProps,
  useRestyle,
  spacing,
  border,
  backgroundColor,
  BorderProps,
  BackgroundColorProps,
  createVariant,
  VariantProps,
} from "@shopify/restyle";
import { TextInput as RNTextInput } from "react-native";
import { Theme } from "styles/theme";

type TextInputProps = React.ComponentPropsWithRef<typeof RNTextInput> &
  BorderProps<Theme> &
  BackgroundColorProps<Theme> &
  ColorProps<Theme> &
  VariantProps<Theme, "textInputVariants"> & {
    error?: string | boolean;
  };

const variant = createVariant<Theme>({
  themeKey: "textInputVariants",
  defaults: {
    width: "100%",
    borderRadius: 10,
    backgroundColor: "mainBackground",
  },
});
const restyleFunctions = [spacing, border, backgroundColor, variant];

export const TextInput = forwardRef<RNTextInput, TextInputProps>(
  ({ ...rest }, ref) => {
    const props = useRestyle(restyleFunctions as any, rest);
    return <RNTextInput ref={ref} {...props} />;
  },
);

```
I have marked is as any for now, but i think this should be fixed as well.

<img width="781" alt="Screenshot 2020-08-11 at 4 49 00 PM" src="https://user-images.githubusercontent.com/38377482/89891409-a11fb600-dbf2-11ea-8a95-fa3923466971.png">

**Comment by JoelBesada** [comment]
@sarmad1995 Thanks for reporting, looks like we're missing a forwardRef wrapper around createBox and createText, I'll fix this when I get the chance. As for the TypeScript issue with your restyleFunctions list, it's related to this #34 and will be fixed soon as well!
