### ISSUE TITLE
Typing of backgroundColor is incorrect when no breakpoints are defined

### ISSUE THREAD

**Issue by wcandillon** [Shopify/restyle#44]
if the theme defines `breakpoints` as `{}`, the typing of backgroundColor will accept any value. When a key is set in `breakpoints`, everything is good.

**Comment by JoelBesada** [comment]
Hmm, this seems to be caused by this type which wraps all property types, but I don't quite see why an empty breakpoints object would cause it to accept any type of value: 

https://github.com/Shopify/restyle/blob/51156537fa1212027ebbe4b6f3b5850d89b00b3e/src/types.ts#L3-L5
