### ISSUE TITLE
How can  I make a "base" variant that multiple variants will extend it?

### ISSUE THREAD

**Issue by Newbie012** [Shopify/restyle#49]
I have `buttonVariants` object which has `.primary`, `.secondary`. Both of these variants have a shared style in common. So I thought about adding another variant called `.base` so they can extend from. Is it possible to do so?

**Comment by Johan-dutoit** [comment]
I only noticed this issue now, however I've created a [PR](https://github.com/Shopify/restyle/pull/51) that does just this!

Instead of .base it uses .defaults, to match the naming from `createVariant`.

**Comment by Newbie012** [comment]
Thanks, really appreciated :)
