### ISSUE TITLE
Use different style depend on platform

### ISSUE THREAD

**Issue by yjose** [Shopify/restyle#52]
Hey 👋, first of all, thanks for this wonderful library. 

Some time I would love to use different styles depending on the OS platform ( android/ios), that way I suggest if we can have a way to do it like the responsive utility.

**Comment by JoelBesada** [comment]
Hi, thank you! I think using `Platform.select` (https://reactnative.dev/docs/platform-specific-code#platform-module) should be enough to fill this use case for now: 

```tsx
<Text fontSize={Platform.select({ios: 16, android: 18})}>Hello</Text>
```

**Comment by yjose** [comment]
thanks @JoelBesada
