### ISSUE TITLE
Examples of createRestyleComponent in readme out of date

### ISSUE THREAD

**Issue by jtstodola** [Shopify/restyle#54]
The current readme documentation on createRestyleComponent is out of date. Starting with version 1.2.0 you have to pass a theme type as well, otherwise you get an error of `Expected 2 type arguments, but got 1.`

```
const Card = createRestyleComponent<
  VariantProps<Theme, 'cardVariants'> & React.ComponentProps<typeof Box>,
  Theme
>([createVariant({themeKey: 'cardVariants'})], Box);
```

**Comment by flexbox** [comment]
Hey @jtstodola 
I think this https://github.com/Shopify/restyle/commit/ee01e030a11252444e406293d27437cb98234bb3 fixed the problem
Can you please close the issue if it's the case 😉

**Comment by jtstodola** [comment]
Perfect, thanks!!
