### ISSUE TITLE
Package fails yarn tsc

### ISSUE THREAD

**Issue by AAfify1** [Shopify/restyle#56]
Yarn tsc produces 2 errors as shown in the screenshot, any idea how to fix this?
![Screen Shot 2020-10-01 at 2 25 16 PM](https://user-images.githubusercontent.com/15859023/94808893-18ebaf00-03f2-11eb-87d9-9d439083440b.png)

**Comment by JoelBesada** [comment]
Hmm these are dist files that shouldn't really be type checked like this. I would suggest excluding `tsc` from running on anything in node_modules, see the example here https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#examples.

**Comment by AAfify1** [comment]
Thank you managed to fix it by adding `"skipLibCheck": true` to my `tsconfig.json`
