### ISSUE TITLE
I like the way, styling in react native is handled here! Do you need help with anything ? 

### ISSUE THREAD

**Issue by roshangm1** [Shopify/restyle#6]

**Comment by JoelBesada** [comment]
Help is always 100% appreciated! We don't have a concrete roadmap for future additions to the library right now, but if there are any bugs that need to be fixed or parts of the documentation that can be made better, we're happy to accept any contributions.

**Comment by roshangm1** [comment]
Sure thanks!! Do let know when you have any kind of plans on new features or anything. Also, I will be using this in my next project and If any bug arises, I can contribute by sending a PR there. 
Thanks for replying @JoelBesada Closing this issue for now.
