### ISSUE TITLE
Is there a plan to introduce more functions like createBox within the library? 

### ISSUE THREAD

**Issue by roshangm1** [Shopify/restyle#8]
I was wondering if there is any plan for introducing other functions like createCard, createImage, createButton with default variants and styles within the library so that developers who wants standard default design don't have to create their own ? @JoelBesada

**Comment by roshangm1** [comment]
Much like how other UI libraries does.

**Comment by JoelBesada** [comment]
What's a bit different with Restyle compared to other UI libraries is that we only intend to provide the basic building blocks for users of the library to build their own UI components with. For that purpose, `createText` and `createBox` should be enough. 

However, I think there's definitely room for separate libraries built on top of Restyle that provide components that come with more styling and logic built in by default, like the ones you are suggesting.

**Comment by roshangm1** [comment]
@JoelBesada I completely understand that. Closing this issue.
