### ISSUE TITLE
what is the right way to use restyle with styled-component?

### ISSUE THREAD

**Issue by chj-damon** [Shopify/restyle#97]
in regular restyle component, I can use theme like this:
```tsx
export default () => {
    const theme = useTheme();
    return <View style={{ backgroundColor: theme.colors.background }}><Text>123</Text></View>
}
```

I can also use `styled-component` in my project like this:
```tsx
import styled from 'styled-component';

export default () => {
    return <Wrapper><Text>123</Text></Wrapper>
}

const Wrapper = styled.View`
    backgroundColor: '#fff'
`
```

I want to use both `styled-component` and `restyle` at the same time, what should I do?

**Comment by dobrea-v** [comment]
@chj-damon Yes you can use restyle theme in styled-components, but obviously without benefits of accessing by tokens.

So this would work: 

```
const Wrapper = styled.View`
    backgroundColor: theme.colors.white
`
```

Also you can similarly create your wrapper component like this instead of SC:

```
export const Wrapper: React.FC = ({children}) => {
  return (
    <Box p='m' backgroundColor='white'>
      {children}
    </Box>
  );
};
```

**Comment by chj-damon** [comment]
Thanks.
